# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        product:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Product
                provider: ~
                finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            default:
                                type: custom
                                tokenizer: lowercase
                                filter: [ my_ngram ]
                        filter:
                            my_ngram:
                                type: "nGram"
                                min_gram: 3
                                max_gram: 4
            properties:
                name: ~
                description: ~
                productCategory:
                    type: 'nested'
                    properties:
                        name: ~
